trigger:
- none

pr:
- master

pool:
  vmImage: windows-latest

jobs:
  - job: BuildTestPublish
    displayName: Build
    steps:
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: '*konopka.service?/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: Tests
        inputs:
          command: 'test'
          projects: '*tests/*.csproj'