trigger:
- none

pr:
- master

pool:
  vmImage: windows-latest

jobs:
  - job: BuildTest
    displayName: BuildTest
    steps:
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: '*konopka.service?/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: Tests
        inputs:
          command: 'test'
          projects: '*tests/*.csproj'
  - job: Container1
    dependsOn: BuildTest
    displayName: Container1
    steps:
      - task: Docker@2
        displayName: Container1
        inputs:
          containerRegistry: 'dockerHub'
          repository: 'skinex/simplewebapp1'
          command: 'buildAndPush'
          Dockerfile: '*1/Dockerfile'
          tags: '$(Build.BuildNumber)'
  - job: Container2
    dependsOn: BuildTest
    displayName: Container2
    steps:
      - task: Docker@2
        displayName: Container2
        inputs:
          containerRegistry: 'dockerHub'
          repository: 'skinex/simplewebapp2'
          command: 'buildAndPush'
          Dockerfile: '*2/Dockerfile'
          tags: '$(Build.BuildNumber)'
  - job: Container3
    dependsOn: BuildTest
    displayName: Container3
    steps:
      - task: Docker@2
        displayName: Container3
        inputs:
          containerRegistry: 'dockerHub'
          repository: 'skinex/simplewebapp3'
          command: 'buildAndPush'
          Dockerfile: '*3/Dockerfile'
          tags: '$(Build.BuildNumber)'