trigger:
- none

pr:
- master

pool:
  vmImage: windows-latest

jobs:
  - job: BuildTestPublish
    displayName: Build
    steps:
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: 'build'
          projects: '*konopka.service?/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: Tests
        inputs:
          command: 'test'
          projects: '*tests/*.csproj'
      - task: Docker@2
        displayName: Container1
        inputs:
          containerRegistry: 'dockerHub'
          repository: 'simplewebapp'
          command: 'buildAndPush'
          Dockerfile: '*1/Dockerfile'
      - task: Docker@2
        displayName: Container2
        inputs:
          containerRegistry: 'dockerHub'
          repository: 'simplewebapp'
          command: 'buildAndPush'
          Dockerfile: '*2/Dockerfile'
      - task: Docker@2
        displayName: Container3
        inputs:
          containerRegistry: 'dockerHub'
          repository: 'simplewebapp'
          command: 'buildAndPush'
          Dockerfile: '*3/Dockerfile'